# Generated by Django 3.2.3 on 2021-07-25 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0002_details_educationdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='details',
        ),
        migrations.DeleteModel(
            name='educationdetails',
        ),
    ]
